pipeline:
  name: Mission14
  identifier: Mission14
  projectIdentifier: SonarQube_Test_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Mission14_Connector
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: scan python-flask codebase
        identifier: scan_pythonflask_codebase
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Sonarqube
                  name: Sonarqube scan
                  identifier: Sonarqube_scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: low
                    connectorRef: account.harnessImage
                    auth:
                      access_token: <+secrets.getValue("org.sonar-global-token")>
                      domain: http://35.206.188.23:9000/
                      ssl: true
                    tool:
                      project_key: python-flask-project
              - step:
                  type: Run
                  name: get quality gate
                  identifier: get_quality_gate
                  spec:
                    shell: Bash
                    command: |-
                      token='<+secrets.getValue("org.sonar-global-token")'
                      echo "Token"
                      echo $token
                      curl -k -u ${token}: -G --data-urlencode --data-urlencode http://35.206.188.23:9000/api/qualitygates/project_status?projectKey=python-flask-project
